Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.provider "virtualbox" do |vb|

     vb.gui = true

     vb.cpus = 2

     vb.memory = "2048"

     vb.name = "ICSE-2012-EXSYST"

   end

  config.vm.provision "shell", inline: <<-SHELL

     sudo add-apt-repository -y ppa:webupd8team/java

     sudo apt-get update

     echo "oracle-java6-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
     
     sudo apt-get install -y oracle-java6-installer

     sudo apt-get install -y ubuntu-desktop

     sudo gsettings set org.gnome.desktop.screensaver lock-enabled false

     sudo reboot

  SHELL

end